### ISSUE TITLE
Replication fails and server gets stuck after many hours running

### ISSUE THREAD

**Issue by rogeriochaves** [rogeriochaves/feedless#14]
I've noticed ssb webserver gets stuck with this error message from time to time, it's been happening every day now:

```
Error replicating with @lYpYpOlnvZplcadel54guQRT0xRzT1Qx06bEQOnlL4w=.ed25519:
   Error: stream ended with:2 but wanted:34
    at drain (/app/node_modules/pull-reader/index.js:43:26)
    at /app/node_modules/pull-reader/index.js:63:18
    at /app/node_modules/pull-reader/index.js:114:13
    at drain (/app/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/app/node_modules/stream-to-pull-stream/index.js:143:5)
    at Socket.emit (events.js:198:15)
    at Socket.EventEmitter.emit (domain.js:481:20)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
Error replicating with @H9MGs3rgWcIbyYAm25EjsE8i01YRIpUVL3tf3gJofMM=.ed25519:
   Error: stream ended with:2 but wanted:34
    at drain (/app/node_modules/pull-reader/index.js:43:26)
    at /app/node_modules/pull-reader/index.js:63:18
    at /app/node_modules/pull-reader/index.js:114:13
    at drain (/app/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/app/node_modules/stream-to-pull-stream/index.js:143:5)
    at Socket.emit (events.js:198:15)
    at Socket.EventEmitter.emit (domain.js:481:20)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
server error, from net:77.251.152.219:62344~shs:
Error: stream ended with:0 but wanted:64
    at drain (/app/node_modules/pull-reader/index.js:43:26)
    at /app/node_modules/pull-reader/index.js:63:18
    at /app/node_modules/pull-reader/index.js:20:7
    at drain (/app/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/app/node_modules/stream-to-pull-stream/index.js:147:5)
    at Socket.emit (events.js:198:15)
    at Socket.EventEmitter.emit (domain.js:481:20)
    at TCP._handle.close (net.js:614:12)
```

The process don't die by its own, restarting manually works but ideally it would self-recover

**Comment by rogeriochaves** [comment]
Fixed by throwing when there is a "stream ended" error from ssb-server, causing process to die and be restarted:

https://github.com/rogeriochaves/feedless/blob/f5be43de9561f7742e2db997b241c206449359d2/web/lib/ssb-config.js#L8

unfortunately I had to patch secret-stack for that to work:

https://github.com/rogeriochaves/feedless/blob/f5be43de9561f7742e2db997b241c206449359d2/web/apply-patches.sh#L3
